namespace Repository.Entities
{
    public class HealthRiskAssessment
    {
        public string Question1Text { get; set; }
        public int Question1YesCount { get; set; }
        public string Question2Text { get; set; }
        public int Question2YesCount { get; set; }
        public string Question3Text { get; set; }
        public int Question3YesCount { get; set; }
        public string Question4Text { get; set; }
        public int Question4YesCount { get; set; }
        public string Question5Text { get; set; }
        public int Question5YesCount { get; set; }
        public string Question6Text { get; set; }
        public int Question6YesCount { get; set; }
        public string Question7Text { get; set; }
        public int Question7YesCount { get; set; }
        public string Question8Text { get; set; }
        public int Question8YesCount { get; set; }
        public string Question9Text { get; set; }
        public int Question9YesCount { get; set; }
        public string Question10Text { get; set; }
        public int Question10YesCount { get; set; }
        public string Question11Text { get; set; }
        public int Question11YesCount { get; set; }
        public string Question12Text { get; set; }
        public int Question12YesCount { get; set; }
        public string Question13Text { get; set; }
        public int Question13YesCount { get; set; }
        public string Question14Text { get; set; }
        public int Question14YesCount { get; set; }
        public string Question15Text { get; set; }
        public int Question15YesCount { get; set; }
        public string Question16Text { get; set; }
        public int Question16YesCount { get; set; }
        public string Question17Text { get; set; }
        public int Question17YesCount { get; set; }
        public string Question18Text { get; set; }
        public int Question18YesCount { get; set; }
        public string Question19Text { get; set; }
        public int Question19YesCount { get; set; }
        public string Question20Text { get; set; }
        public int Question20YesCount { get; set; }
        public string Question21Text { get; set; }
        public int Question21YesCount { get; set; }
        public string Question22Text { get; set; }
        public int Question22YesCount { get; set; }
        public string Question23Text { get; set; }
        public int Question23YesCount { get; set; }
        public string Question24Text { get; set; }
        public int Question24YesCount { get; set; }
        public string Question25Text { get; set; }
        public int Question25YesCount { get; set; }
        public string Question26Text { get; set; }
        public int Question26YesCount { get; set; }
        public string Question27Text { get; set; }
        public int Question27YesCount { get; set; }
        public string Question28Text { get; set; }
        public int Question28YesCount { get; set; }
        public string Question29Text { get; set; }
        public int Question29YesCount { get; set; }
        public string Question30Text { get; set; }
        public int Question30YesCount { get; set; }
        public string Question31Text { get; set; }
        public int Question31YesCount { get; set; }
        public string Question32Text { get; set; }
        public int Question32YesCount { get; set; }
        public string Question33Text { get; set; }
        public int Question33YesCount { get; set; }
        public string Question34Text { get; set; }
        public int Question34YesCount { get; set; }
        public string Question35Text { get; set; }
        public int Question35YesCount { get; set; }
        public string Question36Text { get; set; }
        public int Question36YesCount { get; set; }
        public string Question37Text { get; set; }
        public int Question37YesCount { get; set; }
        public string Question38Text { get; set; }
        public int Question38YesCount { get; set; }
        public string Question39Text { get; set; }
        public int Question39YesCount { get; set; }
    }
}
